---

- name: Ensure php
  pacman: name=php
  tags: packages

- name: Configure php
  template: src=php.ini.j2
            dest=/etc/php/php.ini
            owner=root group=root
  notify: reload webserver
  tags: config

- name: Ensure php libraries
  pacman: name={{ item }}
  with_items:
    - php-apache
    - php-gd
    - php-geoip
    - php-mcrypt
    - php-memcache
    - php-pgsql
    - php-pear
    - php-tidy
    - php-intl
  notify: reload webserver

- name: Enable memcached extension
  lineinfile: dest=/etc/php/conf.d/memcache.ini
              regexp='^;extension'
              line='extension=memcache.so'
  notify: reload webserver
  tags:
    - php
    - memcached
    - config
