---

- name: Ensure php
  apt: name=php5 state=installed
  tags: 
    - php
    - packages

- name: Configure php
  template: src=php.ini.j2
            dest=/etc/php5/apache2/php.ini
            owner=root group=root
  notify: reload webserver
  tags: 
    - php
    - config

- name: Ensure php libraries
  apt: name={{ item }} state=installed
  with_items:
    - libapache2-mod-php5
    - php5-curl
    - php5-gd
    - php5-mcrypt
    - php5-memcache
    - php5-sqlite
    - php5-tidy
    - php5-xmlrpc
    - php5-json
    - php5-pgsql
#    - php5-geoip
#    - php5-intl
#    - php-pear
  notify: reload webserver
  tags:
    - php
    - packages
